time|level|timeoffset|message|location
082515_112840.859|INFO|000.000486| Software version: Plus-2.3.0.4221 - Linux| in vtkPlusLogger(183)
082515_112840.859|INFO|000.000583| Logging at level 3 (INFO) to file: /home/snr/Support/Plus-build-codeblocks/bin/Output/082515_112840_PlusLog.txt| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/PlusServer/Testing/PlusServer.cxx(85)
082515_112849.958|ERROR|009.099277| Cannot connect to the server (170.223.221.150:18944).| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/DataCollection/OpenIGTLink/vtkOpenIGTLinkDevice.cxx(138)
082515_112849.958|ERROR|009.099399| TrackerDevice: Cannot connect to data source, ConnectInternal failed| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/DataCollection/vtkPlusDevice.cxx(959)
082515_112849.958|ERROR|009.099449| Unable to connect device: TrackerDevice.| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/DataCollection/vtkDataCollector.cxx(306)
082515_112849.958|ERROR|009.099525| Datacollector failed to connect to devices| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/PlusServer/Testing/PlusServer.cxx(132)
